### ISSUE TITLE
How to Debug in Visual Studio Code with jetty 

### ISSUE THREAD

**Issue by Flouse** [kasecato/vscode-javadebug-sample#2]
I have maven project with plugin: 
`
<groupId>org.eclipse.jetty</groupId>
<artifactId>jetty-maven-plugin</artifactId>
`
now i Don't know how to Debug in Visual Studio Code with jetty ?
Would you please give me some keywords for searching?

**Comment by kasecato** [comment]
@Flouse Just keywords...
- Setting debug configuration for maven+jetty+eclipse, https://stackoverflow.com/a/20171100/3431033
- Java Attach to Remote Process, https://code.visualstudio.com/blogs/2017/09/28/java-debug#_supported-features

**Comment by kasecato** [comment]
@Flouse I created jetty sample with maven;
https://github.com/kasecato/vscode-javadebug-sample/tree/maven-jetty

**Comment by Flouse** [comment]
@kasecato  It works.
You are very nice!
